---
- name: Clone dotfiles
  git:
    repo: git@github.com:zachatttack/.dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    clone: true

- name: Download oh my zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh
    mode: 0700

- name: delete .ohmyzsh
  ansible.builtin.file:
    path: /home/zach/.oh-my-zsh
    state: absent

- name: Install oh my zsh
  shell:
    cmd: /tmp/ohmyzsh.sh

- name: delete .zshrc
  ansible.builtin.file:
    path: $HOME/.zshrc
    state: absent

- name: Stow zsh
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow zsh"

- name: Stow zprofile
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow zprofile"

- name: Clone tmux sample config
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "$HOME/.tmux"
    clone: true
      
- name: link tmux 
  shell:
    chdir: "$HOME/.tmux"
    cmd: "ln -s -f $HOME/.tmux/.tmux.conf $HOME/.tmux.conf"


- name: Stow tmux
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow tmux"
