---
- name: Clone dotfiles
  git:
    repo: https://github.com/zachatttack/.dotfiles
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    clone: true

- name: zsh submodules 
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "git submodule update --init"

- name: Stow zsh
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow zsh"

- name: Install starship.rs
  shell:
    cmd: curl -sS https://starship.rs/install.sh | sh

- name: Stow zprofile
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow zprofile"

- name: Clone tmux sample config
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "$HOME/.tmux"
    clone: true
      
- name: link tmux 
  shell:
    chdir: "$HOME/.tmux"
    cmd: "ln -s -f $HOME/.tmux/.tmux.conf $HOME/.tmux.conf"

- name: Stow tmux
  shell:
    chdir: $HOME/.dotfiles/
    cmd: "stow tmux"
