---
- name: Remove neovim
  become: true
  shell: rm -rf /home/zach/src/nvim
  tags:
    - neovim

- name: Clone nvim repository
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_env.HOME }}/src/nvim"
  register: nvim
  tags:
    - neovim

- name: Install nvim build dependencies
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
    state: present
  tags:
    - neovim

- name: Build nvim release version
  become: true
  make:
    chdir: "{{ ansible_env.HOME }}/src/nvim"
    target: install
    params:
      NUM_THREADS: 8
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: nvim.changed
  tags:
    - neovim

- name: Clone neovim config
  git:
    repo: https://github.com/zachatttack/nvim_config
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    clone: true
