---
- name: copy public key
  copy:
    src: files/id_ed25519.pub
    dest: $HOME/.ssh/id_ed25519.pub

- name: copy private key
  copy:
    src: files/id_ed25519
    dest: $HOME/.ssh/id_ed25519
    mode: '0600'
